#!/usr/bin/env bash

# Install Gunicorn and any other libraries required by your application
sudo apt-get update
sudo apt-get install -y python3-pip
sudo pip3 install gunicorn

# Clone your AirBnB_clone_v2 repository
git clone https://github.com/username/AirBnB_clone_v2.git ~/AirBnB_clone_v2

# Navigate to the repository directory
cd ~/AirBnB_clone_v2

# Bind Gunicorn instance to localhost on port 5000 with your application object as the entry point
gunicorn --bind 0.0.0.0:5000 web_flask.0-hello_route:app
